### ISSUE TITLE
Very strict command parser to determine execution type (Shell, exec, EPN or internal)

### ISSUE THREAD

**Issue by nook24** [ConSol-Monitoring/mod-gearman-worker-go#22]
Currently the worker makes use of a very restrictive way of determining if a command should be executed through a shell, exec or EPN. 
I noticed this while I was playing around with the `check_nwc_health` plugin. It supports arguments like this: `--warningx ".*usage.*"=$ARG2$ --criticalx ".*usage.*"=$ARG3$`.  Due to the command contains a `*`, it will not use EPN but the shell instead.

https://github.com/ConSol-Monitoring/mod-gearman-worker-go/blob/04cdf5304a49537177fb1a494fe1fd7522def188/command.go#L51-L53

Honestly speaking I'm not sure what would be a good solution to resolve this.

**Comment by sni** [comment]
this should work much better with the next release. Basically everything in single quote will be ignored then. So your example should be passed to the epn worker then.

**Comment by nook24** [comment]
Thanks :)
