### ISSUE TITLE
Misplacing of worker name in 1.5.1

### ISSUE THREAD

**Issue by snarf6** [ConSol-Monitoring/mod-gearman-worker-go#30]
Hello,

I've noticed that the patch fixing #27 added a bug in case the plugin have perfadata. 

ex: 

`DISK OK - free space: / 8000 MB (56% inode=90%);| /=6273MB;9939;13011;0;15059 (worker: XXXXXXXXX)`

In this case, the added `config.identifier` is after the `|`, so it's not visible in WUI (ie thruk) if the plugin returns perfdatas

I see 2 options here : 

* putting the `config.identifier` at the right place ( using the [nagios plugin api](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/pluginapi.html) for handling long output)
* putting worker name back at the begining of the plugin output (and make it consistent to the classical mod-gearman-worker implementation)

I'm not used to code in go, so , if i make a PR, that would not be best-pratice-coded ;)

Thx.

**Comment by divinesecret** [comment]
It is visible if expanded. Anyway, i want to maintain the worker name at the end of visible output, thus experimenting a bit with handling perdata part e.g.:
```
 		if config.workerNameInResult {
-			result.output = fmt.Sprintf("%s (worker: %s)", result.output, config.identifier)
+			outputparts := strings.SplitN(result.output, "|", 2)
+			if len(outputparts) > 1 {
+				result.output = fmt.Sprintf("%s (worker: %s) |%s", outputparts[0], config.identifier, outputparts[1])
+			} else {
+				result.output = fmt.Sprintf("%s (worker: %s)", result.output, config.identifier)
+			}
```

Basically it notices that perfdata is being pushed by searching for delimiter '|', then the result is being split into parts and perfdata is being handled correctly while leaving the `config.identifier` just before that perfdata starts. So far it worked nicely. If it suits you i could make PR out of this if you don't see any caveats here.

**Comment by sni** [comment]
looks good, please create a PR for this.

**Comment by snarf6** [comment]
(back from holidays)

beware about perfdatas . in case of multiline output and multi perfdata, you could have 2 `|` separators 

here the sample from the [nagios API spec](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/pluginapi.html)

```
TEXT OUTPUT | OPTIONAL PERFDATA
LONG TEXT LINE 1
LONG TEXT LINE 2
...
LONG TEXT LINE N | PERFDATA LINE 2
PERFDATA LINE 3
...
PERFDATA LINE N
```
I think that safer to move it on the beginning of the output. That's what i've proposed in [PR31](https://github.com/ConSol-Monitoring/mod-gearman-worker-go/pull/31/files).

(Even it's a trival update, i have to test it on prod here)

**Comment by divinesecret** [comment]
In this case the first separator will always be used for 'where to place worker name' i.e. it does not matter how many layers of perf data comes after the first separator.
The problem with "beginning of the output" is that if worker names are long hostnames it clogs the view for Operation teams that work with GUIs and mostly just want to see the plugin output in the first part of the view.

**Comment by snarf6** [comment]
I understand this, but, in some cases (old things involving 1k NRPE output, or very long one > 4k - ie ugly stacktrace in output), putting it at the end may lead to lose the worker identifier information. 

This would make the debug quite harder when you have many workers

A choice has to be done, probably by  @sni :)
(or a more complex implementation involving a placement config )

**Comment by divinesecret** [comment]
Probably could be two variables, one that enables the worker output like now (i.e. `worker_name_in_result`), and the supplementary variable that defines whether to put it at the beginning or at the end of 'TEXT OUTPUT' (e.g. worker_name_in_result_position=pre_output/pre_perfdata, while documenting in comments how that works). Just need to think about naming, which is the hardest part in IT :)

**Comment by divinesecret** [comment]
Updated the PR with an  option of `worker_name_in_result_position`. By default the worker name will be displayed at the beginning of the output (pre_output option). Additionally it has pre_perfdata option which places the worker name at the end of plugin text output, but before perfdata.

**Comment by sni** [comment]
i'd prefer a single option `worker_name_in_result` with just 3 options, on/off/front or something like that. Or what's the benefit of having two options for a single thing.

**Comment by sni** [comment]
Besides that, this option was never meant to be permanently enabled. Its purpose is to temporarily debug issues.
Then there is a (probably not yet completed) way to have this information permanently available. Naemon has a attribute "check engine" which will be filled with the last worker
name. It is just not displayed anywhere because is such a rare corner case.
So if you need to have this information permanently available, i'd suggest going that way.

**Comment by divinesecret** [comment]
Updated PR #33 with single variable with different options.

p.s. would need some time to get to know Naemon code and how to go about it, so if possible for now it would be nice to have such option in gearman worker.
