### ISSUE TITLE
debug-result option

### ISSUE THREAD

**Issue by abroc** [ConSol-Monitoring/mod-gearman-worker-go#7]
Hi,
we are running mod-gearman worker go in omd-labs 2.90 with "debug-result=yes" option, but in output of plugin we are not able to see hostname of the worker.
With old mod-gearman worker debug-result option is working fine.

Thanks,
Jan

**Comment by sni** [comment]
this option has never been implemented in the go worker.

**Comment by sni** [comment]
this has been implemented with #27
